<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Throne.Application\Throne.Application.csproj" />
    <ProjectReference Include="..\Throne.Infrastructure\Throne.Infrastructure.csproj" />
    <ProjectReference Include="..\Throne.Intents.Contracts\Throne.Intents.Contracts.csproj" />
    <ProjectReference Include="..\Throne.Instructions.Contracts\Throne.Instructions.Contracts.csproj" />
    <ProjectReference Include="..\Throne.Realtime.Contracts\Throne.Realtime.Contracts.csproj" />
    <ProjectReference Include="..\Throne.Tags.Contracts\Throne.Tags.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

</Project>
