<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Throne.Application\Throne.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="SharpToken" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

</Project>
