<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Throne.Mcp.Stdio</AssemblyName>
    <RootNamespace>Throne.Mcp.Stdio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Throne.Api\Throne.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Throne.Api\appsettings.json" Link="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Throne.Api\appsettings.Development.json" Link="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
